# Generated by Django 3.2.3 on 2021-07-04 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_iris', models.IntegerField(default=0)),
                ('Nome', models.CharField(max_length=200)),
                ('data_registro', models.DateField(default=datetime.date.today)),
                ('upload', models.FileField(upload_to='E:\\TCC\\image_iris')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
