# Generated by Django 3.2.3 on 2021-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_auto_20210704_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iris',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='iris',
            name='id_iris',
        ),
        migrations.AddField(
            model_name='iris',
            name='password',
            field=models.CharField(default='123', max_length=30),
        ),
        migrations.AddField(
            model_name='iris',
            name='usuario',
            field=models.CharField(default='user', max_length=30),
        ),
    ]
