# Generated by Django 3.2.3 on 2021-10-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0003_auto_20210908_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='chave_privada',
            field=models.CharField(default='chave', max_length=30),
        ),
        migrations.AlterField(
            model_name='iris',
            name='upload',
            field=models.FileField(upload_to='E:\\TCCIRIS\\Projeto\\mysite\\iris\\image_iris'),
        ),
    ]
