# Generated by Django 3.2.3 on 2021-10-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0004_auto_20211010_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='iris',
            name='chave_publica',
            field=models.CharField(default='chave', max_length=100),
        ),
        migrations.AlterField(
            model_name='iris',
            name='chave_privada',
            field=models.CharField(default='chave', max_length=100),
        ),
    ]
