# Generated by Django 3.2.3 on 2021-10-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0006_auto_20211018_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iris',
            old_name='iris_code',
            new_name='iris_codep1',
        ),
        migrations.AddField(
            model_name='iris',
            name='iris_codep2',
            field=models.CharField(default='0101010', max_length=1000),
        ),
        migrations.AlterField(
            model_name='iris',
            name='upload',
            field=models.CharField(default='Amostra1.jpg', max_length=100),
        ),
    ]
